### PR TITLE
Added resources from Week 1

### PR DESCRIPTION
**Pull request by YehorBoiar**
Added resources from teams week 1 conversation to README.md file

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Hi Yehor,

Thanks for this! Though I intended to suggest using the wiki for this. Maybe you don't have access to it? If so I can give you access. It should be a tab in this VIP repository.

**Comment by YehorBoiar** [comment]
I think I don't have an access to it, you're right. When I go to /VIP/wiki it navigates me to just /VIP

**Comment by ozgurakgun** [comment]
I'll close this PR, you should be able to see/edit the Wiki now - hopefully!

**Comment by YehorBoiar** [comment]
Closed as I received rights for wiki

**Pull request closed without merging**
